version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: tedelimon-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www
  nginx:
    image: nginx:latest
    container_name: tedelimon-nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
